# Generated by Django 4.2.7 on 2023-12-08 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('short_title', models.CharField(max_length=40)),
                ('category',
                 models.CharField(choices=[('S', 'Sports'), ('P', 'Political'), ('E', 'Economic'), ('C', 'Cultural')],
                                  max_length=1)),
                ('short_content', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('dateOfCreate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000),
                                                           django.core.validators.MaxValueValidator(5000)])),
                ('dateOfEmp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
